export interface Movie {
  adult: boolean
  backdrop_path: null | string
  belongs_to_collection: BelongsToCollection | null
  budget: number
  genres: Genre[]
  homepage: string
  id: number
  imdb_id: null | string
  original_language: OriginalLanguage
  original_title: string
  overview: string
  popularity: number
  poster_path: null | string
  production_companies: ProductionCompany[]
  production_countries: ProductionCountry[]
  release_date: string
  revenue: number
  runtime: number
  spoken_languages: SpokenLanguage[]
  status: Status
  tagline: string
  title: string
  video: boolean
  vote_average: number
  vote_count: number
}

export interface BelongsToCollection {
  id: number
  name: string
  poster_path: null | string
  backdrop_path: null | string
}

export interface Genre {
  id: number
  name: GenreName
}

export enum GenreName {
  Action = 'Action',
  Adventure = 'Adventure',
  Animation = 'Animation',
  Comedy = 'Comedy',
  Crime = 'Crime',
  Documentary = 'Documentary',
  Drama = 'Drama',
  Family = 'Family',
  Fantasy = 'Fantasy',
  History = 'History',
  Horror = 'Horror',
  Music = 'Music',
  Mystery = 'Mystery',
  Romance = 'Romance',
  ScienceFiction = 'Science Fiction',
  TVMovie = 'TV Movie',
  Thriller = 'Thriller',
  War = 'War',
  Western = 'Western'
}

export enum OriginalLanguage {
  AF = 'af',
  AV = 'av',
  Aa = 'aa',
  Ak = 'ak',
  Am = 'am',
  An = 'an',
  Ar = 'ar',
  Ay = 'ay',
  Az = 'az',
  BI = 'bi',
  Be = 'be',
  Bg = 'bg',
  Bm = 'bm',
  Bn = 'bn',
  Bo = 'bo',
  Br = 'br',
  Bs = 'bs',
  CA = 'ca',
  CN = 'cn',
  CR = 'cr',
  CS = 'cs',
  Ce = 'ce',
  Co = 'co',
  Cv = 'cv',
  Cy = 'cy',
  Da = 'da',
  De = 'de',
  Dz = 'dz',
  Ee = 'ee',
  El = 'el',
  En = 'en',
  Eo = 'eo',
  Es = 'es',
  Et = 'et',
  Eu = 'eu',
  Fa = 'fa',
  Fi = 'fi',
  Fr = 'fr',
  Ga = 'ga',
  Gd = 'gd',
  Gl = 'gl',
  Gn = 'gn',
  Gu = 'gu',
  HT = 'ht',
  Ha = 'ha',
  He = 'he',
  Hi = 'hi',
  Hr = 'hr',
  Hu = 'hu',
  Hy = 'hy',
  ID = 'id',
  Ig = 'ig',
  Io = 'io',
  Is = 'is',
  It = 'it',
  Iu = 'iu',
  Ja = 'ja',
  Jv = 'jv',
  KM = 'km',
  Ka = 'ka',
  Kg = 'kg',
  Kk = 'kk',
  Kn = 'kn',
  Ko = 'ko',
  Ku = 'ku',
  Kw = 'kw',
  LB = 'lb',
  LV = 'lv',
  La = 'la',
  Ln = 'ln',
  Lo = 'lo',
  Lt = 'lt',
  MS = 'ms',
  MT = 'mt',
  Mh = 'mh',
  Mi = 'mi',
  Mk = 'mk',
  Ml = 'ml',
  Mn = 'mn',
  Mo = 'mo',
  Mr = 'mr',
  My = 'my',
  Nb = 'nb',
  Ne = 'ne',
  Nl = 'nl',
  No = 'no',
  Nv = 'nv',
  Ny = 'ny',
  Oc = 'oc',
  Om = 'om',
  PS = 'ps',
  Pa = 'pa',
  Pl = 'pl',
  Pt = 'pt',
  Qu = 'qu',
  Rm = 'rm',
  Ro = 'ro',
  Ru = 'ru',
  Rw = 'rw',
  SE = 'se',
  Sa = 'sa',
  Sc = 'sc',
  Sh = 'sh',
  Si = 'si',
  Sk = 'sk',
  Sl = 'sl',
  Sm = 'sm',
  So = 'so',
  Sq = 'sq',
  Sr = 'sr',
  St = 'st',
  Sv = 'sv',
  Sw = 'sw',
  Ta = 'ta',
  Te = 'te',
  Th = 'th',
  Tl = 'tl',
  Tn = 'tn',
  To = 'to',
  Tr = 'tr',
  Tt = 'tt',
  Tw = 'tw',
  Ty = 'ty',
  Ug = 'ug',
  Uk = 'uk',
  Ur = 'ur',
  Uz = 'uz',
  Vi = 'vi',
  Wo = 'wo',
  Xh = 'xh',
  Xx = 'xx',
  Yi = 'yi',
  Yo = 'yo',
  Zh = 'zh',
  Zu = 'zu'
}

export interface ProductionCompany {
  id: number
  logo_path: null | string
  name: string
  origin_country: OriginCountry
}

export enum OriginCountry {
  AE = 'AE',
  AF = 'AF',
  Ad = 'AD',
  Al = 'AL',
  Am = 'AM',
  Ao = 'AO',
  Ar = 'AR',
  At = 'AT',
  Au = 'AU',
  Aw = 'AW',
  Az = 'AZ',
  BT = 'BT',
  BW = 'BW',
  Ba = 'BA',
  Bb = 'BB',
  Bd = 'BD',
  Be = 'BE',
  Bf = 'BF',
  Bg = 'BG',
  Bn = 'BN',
  Bo = 'BO',
  Br = 'BR',
  Bs = 'BS',
  By = 'BY',
  CA = 'CA',
  CD = 'CD',
  CF = 'CF',
  CM = 'CM',
  CN = 'CN',
  CR = 'CR',
  CS = 'CS',
  Ch = 'CH',
  Ci = 'CI',
  Cl = 'CL',
  Co = 'CO',
  Cu = 'CU',
  Cy = 'CY',
  Cz = 'CZ',
  De = 'DE',
  Dk = 'DK',
  Do = 'DO',
  Dz = 'DZ',
  Ec = 'EC',
  Ee = 'EE',
  Eg = 'EG',
  Empty = '',
  Es = 'ES',
  Et = 'ET',
  Fi = 'FI',
  Fr = 'FR',
  GB = 'GB',
  Ge = 'GE',
  Gf = 'GF',
  Gh = 'GH',
  Gp = 'GP',
  Gr = 'GR',
  Gt = 'GT',
  Hk = 'HK',
  Hn = 'HN',
  Hr = 'HR',
  Hu = 'HU',
  ID = 'ID',
  IL = 'IL',
  IR = 'IR',
  Ie = 'IE',
  In = 'IN',
  Iq = 'IQ',
  Is = 'IS',
  It = 'IT',
  Jm = 'JM',
  Jo = 'JO',
  Jp = 'JP',
  Ke = 'KE',
  Kh = 'KH',
  Kr = 'KR',
  Kw = 'KW',
  Ky = 'KY',
  Kz = 'KZ',
  LB = 'LB',
  LV = 'LV',
  Li = 'LI',
  Lk = 'LK',
  Lr = 'LR',
  Lt = 'LT',
  Lu = 'LU',
  Ly = 'LY',
  MT = 'MT',
  MX = 'MX',
  Ma = 'MA',
  Mc = 'MC',
  Me = 'ME',
  Mh = 'MH',
  Mk = 'MK',
  Mm = 'MM',
  Mn = 'MN',
  Mo = 'MO',
  Mr = 'MR',
  Mu = 'MU',
  Mw = 'MW',
  My = 'MY',
  NI = 'NI',
  NP = 'NP',
  Na = 'NA',
  Nc = 'NC',
  Ng = 'NG',
  Nl = 'NL',
  No = 'NO',
  Nz = 'NZ',
  PE = 'PE',
  PG = 'PG',
  PR = 'PR',
  PS = 'PS',
  Pa = 'PA',
  Ph = 'PH',
  Pk = 'PK',
  Pl = 'PL',
  Pt = 'PT',
  Py = 'PY',
  QA = 'QA',
  Ro = 'RO',
  Rs = 'RS',
  Ru = 'RU',
  Rw = 'RW',
  SE = 'SE',
  Sa = 'SA',
  Sg = 'SG',
  Si = 'SI',
  Sk = 'SK',
  Sn = 'SN',
  Su = 'SU',
  Sv = 'SV',
  Sy = 'SY',
  Tc = 'TC',
  Th = 'TH',
  Tl = 'TL',
  Tn = 'TN',
  Tr = 'TR',
  Tw = 'TW',
  Ua = 'UA',
  Ug = 'UG',
  Us = 'US',
  Uy = 'UY',
  Va = 'VA',
  Ve = 'VE',
  Vn = 'VN',
  Vu = 'VU',
  Xc = 'XC',
  Xg = 'XG',
  Xk = 'XK',
  Yu = 'YU',
  Za = 'ZA',
  Zm = 'ZM',
  Zw = 'ZW'
}

export interface ProductionCountry {
  iso_3166_1: OriginCountry
  name: ProductionCountryName
}

export enum ProductionCountryName {
  Afghanistan = 'Afghanistan',
  Albania = 'Albania',
  Algeria = 'Algeria',
  Andorra = 'Andorra',
  Angola = 'Angola',
  Argentina = 'Argentina',
  Armenia = 'Armenia',
  Aruba = 'Aruba',
  Australia = 'Australia',
  Austria = 'Austria',
  Azerbaijan = 'Azerbaijan',
  Bahamas = 'Bahamas',
  Bangladesh = 'Bangladesh',
  Barbados = 'Barbados',
  Belarus = 'Belarus',
  Belgium = 'Belgium',
  Bhutan = 'Bhutan',
  Bolivia = 'Bolivia',
  BosniaAndHerzegovina = 'Bosnia and Herzegovina',
  Botswana = 'Botswana',
  Brazil = 'Brazil',
  Bulgaria = 'Bulgaria',
  BurkinaFaso = 'Burkina Faso',
  Cambodia = 'Cambodia',
  Cameroon = 'Cameroon',
  Canada = 'Canada',
  CaymanIslands = 'Cayman Islands',
  CentralAfricanRepublic = 'Central African Republic',
  Chile = 'Chile',
  China = 'China',
  Colombia = 'Colombia',
  Congo = 'Congo',
  CostaRica = 'Costa Rica',
  CoteDIvoire = "Cote D'Ivoire",
  Croatia = 'Croatia',
  Cuba = 'Cuba',
  Cyprus = 'Cyprus',
  CzechRepublic = 'Czech Republic',
  Czechoslovakia = 'Czechoslovakia',
  Denmark = 'Denmark',
  DominicanRepublic = 'Dominican Republic',
  EastGermany = 'East Germany',
  Ecuador = 'Ecuador',
  Egypt = 'Egypt',
  ElSalvador = 'El Salvador',
  Estonia = 'Estonia',
  Ethiopia = 'Ethiopia',
  Finland = 'Finland',
  France = 'France',
  FrenchGuiana = 'French Guiana',
  Georgia = 'Georgia',
  Germany = 'Germany',
  Ghana = 'Ghana',
  Greece = 'Greece',
  Guadaloupe = 'Guadaloupe',
  Guatemala = 'Guatemala',
  HolySee = 'Holy See',
  Honduras = 'Honduras',
  HongKong = 'Hong Kong',
  Hungary = 'Hungary',
  Iceland = 'Iceland',
  India = 'India',
  Indonesia = 'Indonesia',
  Iran = 'Iran',
  Iraq = 'Iraq',
  Ireland = 'Ireland',
  Israel = 'Israel',
  Italy = 'Italy',
  Jamaica = 'Jamaica',
  Japan = 'Japan',
  Jordan = 'Jordan',
  Kazakhstan = 'Kazakhstan',
  Kenya = 'Kenya',
  Kosovo = 'Kosovo',
  Kuwait = 'Kuwait',
  Latvia = 'Latvia',
  Lebanon = 'Lebanon',
  Liberia = 'Liberia',
  LibyanArabJamahiriya = 'Libyan Arab Jamahiriya',
  Liechtenstein = 'Liechtenstein',
  Lithuania = 'Lithuania',
  Luxembourg = 'Luxembourg',
  Macao = 'Macao',
  Macedonia = 'Macedonia',
  Malawi = 'Malawi',
  Malaysia = 'Malaysia',
  Malta = 'Malta',
  Mauritania = 'Mauritania',
  Mauritius = 'Mauritius',
  Mexico = 'Mexico',
  Monaco = 'Monaco',
  Mongolia = 'Mongolia',
  Montenegro = 'Montenegro',
  Morocco = 'Morocco',
  Myanmar = 'Myanmar',
  Namibia = 'Namibia',
  Nepal = 'Nepal',
  Netherlands = 'Netherlands',
  NewCaledonia = 'New Caledonia',
  NewZealand = 'New Zealand',
  Nicaragua = 'Nicaragua',
  Nigeria = 'Nigeria',
  Norway = 'Norway',
  Pakistan = 'Pakistan',
  PalestinianTerritory = 'Palestinian Territory',
  Panama = 'Panama',
  PapuaNewGuinea = 'Papua New Guinea',
  Paraguay = 'Paraguay',
  Peru = 'Peru',
  Philippines = 'Philippines',
  Poland = 'Poland',
  Portugal = 'Portugal',
  PuertoRico = 'Puerto Rico',
  Qatar = 'Qatar',
  Romania = 'Romania',
  Russia = 'Russia',
  Rwanda = 'Rwanda',
  SaudiArabia = 'Saudi Arabia',
  Senegal = 'Senegal',
  Serbia = 'Serbia',
  SerbiaAndMontenegro = 'Serbia and Montenegro',
  Singapore = 'Singapore',
  Slovakia = 'Slovakia',
  Slovenia = 'Slovenia',
  SouthAfrica = 'South Africa',
  SouthKorea = 'South Korea',
  SovietUnion = 'Soviet Union',
  Spain = 'Spain',
  SriLanka = 'Sri Lanka',
  Sweden = 'Sweden',
  Switzerland = 'Switzerland',
  SyrianArabRepublic = 'Syrian Arab Republic',
  Taiwan = 'Taiwan',
  Thailand = 'Thailand',
  TimorLeste = 'Timor-Leste',
  Tunisia = 'Tunisia',
  Turkey = 'Turkey',
  TurksAndCaicosIslands = 'Turks and Caicos Islands',
  Uganda = 'Uganda',
  Ukraine = 'Ukraine',
  UnitedArabEmirates = 'United Arab Emirates',
  UnitedKingdom = 'United Kingdom',
  UnitedStatesOfAmerica = 'United States of America',
  Uruguay = 'Uruguay',
  Vanuatu = 'Vanuatu',
  Venezuela = 'Venezuela',
  Vietnam = 'Vietnam',
  Yugoslavia = 'Yugoslavia',
  Zambia = 'Zambia',
  Zimbabwe = 'Zimbabwe'
}

export interface SpokenLanguage {
  english_name: EnglishName
  iso_639_1: OriginalLanguage
  name: SpokenLanguageName
}

export enum EnglishName {
  Afar = 'Afar',
  Afrikaans = 'Afrikaans',
  Akan = 'Akan',
  Albanian = 'Albanian',
  Amharic = 'Amharic',
  Arabic = 'Arabic',
  Aragonese = 'Aragonese',
  Armenian = 'Armenian',
  Avaric = 'Avaric',
  Aymara = 'Aymara',
  Azerbaijani = 'Azerbaijani',
  Bambara = 'Bambara',
  Basque = 'Basque',
  Belarusian = 'Belarusian',
  Bengali = 'Bengali',
  Bislama = 'Bislama',
  Bosnian = 'Bosnian',
  Breton = 'Breton',
  Bulgarian = 'Bulgarian',
  Burmese = 'Burmese',
  Cantonese = 'Cantonese',
  Catalan = 'Catalan',
  Chechen = 'Chechen',
  ChichewaNyanja = 'Chichewa; Nyanja',
  Chuvash = 'Chuvash',
  Cornish = 'Cornish',
  Corsican = 'Corsican',
  Cree = 'Cree',
  Croatian = 'Croatian',
  Czech = 'Czech',
  Danish = 'Danish',
  Dutch = 'Dutch',
  Dzongkha = 'Dzongkha',
  English = 'English',
  Esperanto = 'Esperanto',
  Estonian = 'Estonian',
  Ewe = 'Ewe',
  Finnish = 'Finnish',
  French = 'French',
  Gaelic = 'Gaelic',
  Galician = 'Galician',
  Georgian = 'Georgian',
  German = 'German',
  Greek = 'Greek',
  Guarani = 'Guarani',
  Gujarati = 'Gujarati',
  HaitianHaitianCreole = 'Haitian; Haitian Creole',
  Hausa = 'Hausa',
  Hebrew = 'Hebrew',
  Hindi = 'Hindi',
  Hungarian = 'Hungarian',
  Icelandic = 'Icelandic',
  Ido = 'Ido',
  Igbo = 'Igbo',
  Indonesian = 'Indonesian',
  Inuktitut = 'Inuktitut',
  Irish = 'Irish',
  Italian = 'Italian',
  Japanese = 'Japanese',
  Javanese = 'Javanese',
  Kannada = 'Kannada',
  Kazakh = 'Kazakh',
  Khmer = 'Khmer',
  Kinyarwanda = 'Kinyarwanda',
  Kongo = 'Kongo',
  Korean = 'Korean',
  Kurdish = 'Kurdish',
  Lao = 'Lao',
  Latin = 'Latin',
  Latvian = 'Latvian',
  Letzeburgesch = 'Letzeburgesch',
  Lingala = 'Lingala',
  Lithuanian = 'Lithuanian',
  Macedonian = 'Macedonian',
  Malay = 'Malay',
  Malayalam = 'Malayalam',
  Maltese = 'Maltese',
  Mandarin = 'Mandarin',
  Maori = 'Maori',
  Marathi = 'Marathi',
  Marshall = 'Marshall',
  Moldavian = 'Moldavian',
  Mongolian = 'Mongolian',
  Navajo = 'Navajo',
  Nepali = 'Nepali',
  NoLanguage = 'No Language',
  NorthernSami = 'Northern Sami',
  Norwegian = 'Norwegian',
  Occitan = 'Occitan',
  Oromo = 'Oromo',
  Persian = 'Persian',
  Polish = 'Polish',
  Portuguese = 'Portuguese',
  Punjabi = 'Punjabi',
  Pushto = 'Pushto',
  Quechua = 'Quechua',
  RaetoRomance = 'Raeto-Romance',
  Romanian = 'Romanian',
  Russian = 'Russian',
  Samoan = 'Samoan',
  Sanskrit = 'Sanskrit',
  Sardinian = 'Sardinian',
  Serbian = 'Serbian',
  SerboCroatian = 'Serbo-Croatian',
  Sinhalese = 'Sinhalese',
  Slovak = 'Slovak',
  Slovenian = 'Slovenian',
  Somali = 'Somali',
  Sotho = 'Sotho',
  Spanish = 'Spanish',
  Swahili = 'Swahili',
  Swedish = 'Swedish',
  Tagalog = 'Tagalog',
  Tahitian = 'Tahitian',
  Tamil = 'Tamil',
  Tatar = 'Tatar',
  Telugu = 'Telugu',
  Thai = 'Thai',
  Tibetan = 'Tibetan',
  Tonga = 'Tonga',
  Tswana = 'Tswana',
  Turkish = 'Turkish',
  Twi = 'Twi',
  Uighur = 'Uighur',
  Ukrainian = 'Ukrainian',
  Urdu = 'Urdu',
  Uzbek = 'Uzbek',
  Vietnamese = 'Vietnamese',
  Welsh = 'Welsh',
  Wolof = 'Wolof',
  Xhosa = 'Xhosa',
  Yiddish = 'Yiddish',
  Yoruba = 'Yoruba',
  Zulu = 'Zulu'
}

export enum SpokenLanguageName {
  Afrikaans = 'Afrikaans',
  Azərbaycan = 'Azərbaycan',
  BahasaIndonesia = 'Bahasa indonesia',
  BahasaMelayu = 'Bahasa melayu',
  Bamanankan = 'Bamanankan',
  Bosanski = 'Bosanski',
  Català = 'Català',
  Cymraeg = 'Cymraeg',
  Dansk = 'Dansk',
  Deutsch = 'Deutsch',
  Eesti = 'Eesti',
  Empty = '',
  English = 'English',
  Español = 'Español',
  Esperanto = 'Esperanto',
  Euskera = 'euskera',
  Français = 'Français',
  Gaeilge = 'Gaeilge',
  Galego = 'Galego',
  Hausa = 'Hausa',
  Hrvatski = 'Hrvatski',
  IsiZulu = 'isiZulu',
  Italiano = 'Italiano',
  Kinyarwanda = 'Kinyarwanda',
  Kiswahili = 'Kiswahili',
  Latin = 'Latin',
  Latviešu = 'Latviešu',
  Lietuvių = 'Lietuvių',
  Magyar = 'Magyar',
  Malti = 'Malti',
  Name = '?????',
  Nederlands = 'Nederlands',
  NoLanguage = 'No Language',
  Norsk = 'Norsk',
  Ozbek = 'ozbek',
  Polski = 'Polski',
  Português = 'Português',
  Pусский = 'Pусский',
  Română = 'Română',
  Shqip = 'shqip',
  Slovenčina = 'Slovenčina',
  Slovenščina = 'Slovenščina',
  Somali = 'Somali',
  Srpski = 'Srpski',
  Suomi = 'suomi',
  Svenska = 'svenska',
  TheᲥართული = 'ქართული',
  TiếngViệt = 'Tiếng Việt',
  Türkçe = 'Türkçe',
  Wolof = 'Wolof',
  ÈdèYorùbá = 'Èdè Yorùbá',
  Èʋegbe = 'Èʋegbe',
  Íslenska = 'Íslenska',
  Český = 'Český',
  Ελληνικά = 'ελληνικά',
  БеларускаяМова = 'беларуская мова',
  БългарскиЕзик = 'български език',
  Український = 'Український',
  Қазақ = 'қазақ',
  עִבְרִית = 'עִבְרִית',
  اردو = 'اردو',
  العربية = 'العربية',
  فارسی = 'فارسی',
  پښتو = 'پښتو',
  हिन्दी = 'हिन्दी',
  বাংলা = 'বাংলা',
  ਪੰਜਾਬੀ = 'ਪੰਜਾਬੀ',
  தமிழ் = 'தமிழ்',
  తెలుగు = 'తెలుగు',
  සිංහල = 'සිංහල',
  ภาษาไทย = 'ภาษาไทย',
  广州话廣州話 = '广州话 / 廣州話',
  日本語 = '日本語',
  普通话 = '普通话',
  한국어조선말 = '한국어/조선말'
}

export enum Status {
  InProduction = 'In Production',
  Planned = 'Planned',
  PostProduction = 'Post Production',
  Released = 'Released',
  Rumored = 'Rumored'
}
